### ISSUE TITLE
Add example with cache?

### ISSUE THREAD

**Issue by karlhorky** [ybiquitous/using-nvm-on-github-action#2]
First of all, thanks for this project! I will try it out in our projects because [non-fixed version specifiers do not guarantee new versions in `actions/setup-node`](https://github.com/actions/setup-node/issues/940#issuecomment-2029638604)

[`actions/setup-node`](https://github.com/actions/setup-node) allows for a `cache` configuration, which will save the cache of the package manager:

```yaml
- uses: actions/setup-node@v4
  with:
    cache: 'npm' # also supports 'yarn' and 'pnpm'
```

What do you think about adding an example with caching too?

Implementation ideas:

1. Could use [`actions/cache`](https://github.com/actions/cache)
2. Could use the code from [the examples](https://github.com/actions/cache/blob/main/examples.md#node---npm) and [the latest version from the pnpm readme](https://github.com/pnpm/action-setup/pull/131)
3. Could take ideas from [my `nvm` workflow step example](https://github.com/actions/setup-node/issues/940#issuecomment-2285962305)

**Comment by ybiquitous** [comment]
PR welcome!

**Comment by karlhorky** [comment]
PR open:

- #3
